### ISSUE TITLE
Show playback time when the mouse is hovered to the timeline

### ISSUE THREAD

**Issue by pasxn** [notnavindu/SLIIT-Eduscope-Mods#9]
Eduscope needs a lot of reloading when watching a lecture due to buffering. To jump to the timestamp which the viewer was watching before reloading the page, showing the timestamp when the mouse is hovered to the timeline will be a great feature. 

PS: Would have loved to add this feature and contribute to this project but web technologies  is not my cup of tea. 

Thank you!

**Comment by notnavindu** [comment]
Thanks for the idea @pasxn! I will try to implement this soon

**Comment by notnavindu** [comment]
@pasxn adding the time over hover was kinda complicated so added a feature to save playback time and reload it when you refresh the page. 
(In v3.0.0)

**Comment by pasxn** [comment]
@notnavindu, Yes. That is an even better feature imo. Thank you for helping communities at large by maintaining this project. Cheers!
